services:
  web:
    container_name: apachePHP
    build: .
    ports:
      - "83:80"
    volumes:
      - ./html:/var/www/html
      - ./vhosts.conf:/etc/apache2/sites-available/000-default.conf
      - /var/run/docker.sock:/var/run/docker.sock # allows docker command from Apache to access docker on the host.
    user: www-data
